#!/bin/bash

# source the config file
. backup_tools.config

# find out how many snapshots are currently saved
file_count=$(ls $SNAPSHOT_ARCHIVE | wc -l)

# create a new snapshot
tar -cJf "system_backup_$(date +"%d-%m-%Y").tar.xz" $SYSTEM_BACKUP_TARGET

# move snapshot to archive
mv "system_backup_$(date +"%d-%m-%Y").tar.xz" $SNAPSHOT_ARCHIVE

# if more snapshots saved than expected (default=3),
# then delete the oldest stored snapshot 
if [[ $file_count > $SNAPSHOTS ]]; then
        rm "$SNAPSHOT_ARCHIVE/$(ls $SNAPSHOT_ARCHIVE | head -1)"
fi
