#!/bin/bash

# the location of backup dir
backup_dir="/home/james/LOCAL/github/TempWorkspace/backup"

# location of snapshot archive
snap_arch="/home/james/LOCAL/github/TempWorkspace/archive"

# the number of snapshots to keep 
snapshots=3

# the number of current backups
file_count=$(ls $snap_arch | wc -l)


# check the current number of snapshots 
# and remove the oldest if limit reached
if [[ $file_count > $snapshots ]]; then
        rm "$snap_arch/$(ls $snap_arch | head -1)"
fi

# create a new snapshot
tar -cJf "system_backup_$(date +"%d-%m-%Y").tar.xz" $backup_dir

# move snapshot to archive
mv "system_backup_$(date +"%d-%m-%Y").tar.xz" $snap_arch 
