#! /bin/bash

# source config file
. /etc/backup_tools/backup_tools.conf

# perform backup
rsync $RSYNC_OPTIONS --log-file=$WEEKLY_BACKUP_LOG --exclude-from=$HOME_EXCLUDED $HOMEDIR $WEEKLY_BACKUP_TARGET
